/**
 * Curated activity library. This ships bundled so the app is fully populated on
 * first launch with ZERO network. It is the source of truth the matching engine
 * ranks over; AI-generated activities are added into the same table later.
 *
 * Each entry is hand-authored and already child-safe. `premiumPack` gates the
 * themed packs behind the subscription.
 */
import type { Activity, ActivityDraft } from '@/types/domain';

let counter = 0;
function make(draft: ActivityDraft, premiumPack: string | null = null): Activity {
  counter += 1;
  return {
    ...draft,
    id: `curated-${String(counter).padStart(3, '0')}`,
    source: 'curated',
    status: 'approved',
    premiumPack,
    createdAt: '2026-01-01T00:00:00.000Z',
  };
}

export const CURATED_ACTIVITIES: Activity[] = [
  make({
    title: 'The Great Paper Bridge',
    storyIntro:
      'The river valley needs a bridge! Only the cleverest engineer can build one strong enough for the coin travellers to cross.',
    mission: 'Build a bridge out of paper that spans two stacks of books.',
    objective: 'Can your bridge hold 10 coins without falling?',
    steps: [
      'Set two stacks of books about 20cm apart.',
      'Lay a flat sheet of paper across the gap and add coins one by one. Watch it sag!',
      'Now fold, roll, or shape the paper and try again.',
      'Keep improving until it holds 10 coins.',
    ],
    safetyTips: ['Keep coins away from very young siblings.'],
    learningExplanation:
      'Folding paper into arches or beams makes it far stronger. This is the engineering idea of load and structure.',
    reflectionQuestions: [
      'Why did the flat paper collapse?',
      'What shape made it strongest?',
    ],
    parentTip: "Don't help right away. Ask: 'What could make it stronger?'",
    category: 'engineering',
    skills: ['engineering', 'problem_solving', 'physics'],
    minAge: 5,
    maxAge: 10,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['paper'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'calm',
    difficulty: 'medium',
  }),
  make({
    title: 'Tallest Tower Challenge',
    storyIntro: 'The kingdom needs a lookout tower. Build the tallest one you can before it topples!',
    mission: 'Build the tallest free-standing tower using only paper and tape.',
    objective: 'Make it taller than a water bottle and have it stand for 10 seconds.',
    steps: [
      'Roll paper into tubes or fold it into strong shapes.',
      'Tape pieces together to build upward.',
      'Measure your tower against a bottle.',
      'Try again to beat your own record.',
    ],
    safetyTips: [],
    learningExplanation:
      'A wide, heavy base keeps tall things stable. This is balance and center of gravity.',
    reflectionQuestions: ['What made your tower tip over?', 'How did a wider base help?'],
    parentTip: 'Let them fail a few times. The rebuild is where the learning happens.',
    category: 'engineering',
    skills: ['engineering', 'creativity', 'motor'],
    minAge: 4,
    maxAge: 9,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['paper', 'tape'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'medium',
    difficulty: 'easy',
  }),
  make({
    title: 'Leaf Detective',
    storyIntro: 'Nature left secret clues all over the garden. Can you collect five different leaf shapes?',
    mission: 'Find and sort five leaves that all look different.',
    objective: 'Line up five leaves from smallest to largest.',
    steps: [
      'Go outside and hunt for leaves of different shapes.',
      'Collect five that are clearly different.',
      'Sort them by size, then by shape.',
      'Give each leaf a funny name.',
    ],
    safetyTips: ['Wash hands after touching plants.', 'Only pick fallen leaves.'],
    learningExplanation:
      'Comparing and sorting builds early classification skills, the foundation of biology.',
    reflectionQuestions: ['Which leaf was your favourite and why?', 'What made two leaves different?'],
    parentTip: 'Ask them to guess which tree each leaf came from.',
    category: 'nature',
    skills: ['observation', 'stem', 'motor'],
    minAge: 3,
    maxAge: 8,
    minTime: 15,
    maxTime: 30,
    materialsRequired: [],
    indoorOutdoor: 'outdoor',
    weatherTags: ['sunny', 'windy', 'any'],
    energyLevel: 'medium',
    difficulty: 'easy',
  }),
  make({
    title: 'Rainbow in a Glass',
    storyIntro: 'Sunlight is hiding every colour of the rainbow. Let’s set them free with water!',
    mission: 'Make a rainbow appear using water and sunlight.',
    objective: 'See at least three rainbow colours on the wall or floor.',
    steps: [
      'Fill a clear glass with water and place it near a sunny window.',
      'Put a white sheet of paper on the floor beneath it.',
      'Move the glass until colours appear on the paper.',
      'Trace or point to each colour you find.',
    ],
    safetyTips: ['Wipe up spilled water so no one slips.'],
    learningExplanation:
      'Water bends light and splits it into colours. This is refraction, the same thing a real rainbow does.',
    reflectionQuestions: ['Where did the colours come from?', 'What happened when you moved the glass?'],
    parentTip: 'Best near midday sun. Ask them to predict where the rainbow will land.',
    category: 'science',
    skills: ['stem', 'observation', 'focus'],
    minAge: 4,
    maxAge: 10,
    minTime: 10,
    maxTime: 20,
    materialsRequired: ['water'],
    indoorOutdoor: 'indoor',
    weatherTags: ['sunny', 'hot'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Cardboard Marble Run',
    storyIntro: 'A tiny marble explorer needs a wild ride from the top of the mountain to the bottom!',
    mission: 'Build a track that carries a marble slowly to the floor.',
    objective: 'The marble must travel for at least 5 seconds without falling off.',
    steps: [
      'Cut or fold boxes into ramps and channels.',
      'Tape them to a wall or the side of a table, sloping downward.',
      'Release the marble at the top.',
      'Adjust the slopes so it does not fly off.',
    ],
    safetyTips: ['Marbles are a choking hazard, keep them away from babies.'],
    learningExplanation:
      'Steeper ramps make the marble faster; gentle slopes slow it down. This is gravity and speed.',
    reflectionQuestions: ['Which part was too fast?', 'How did you slow the marble down?'],
    parentTip: 'Ask them to predict before each test run.',
    category: 'engineering',
    skills: ['engineering', 'physics', 'problem_solving'],
    minAge: 6,
    maxAge: 12,
    minTime: 30,
    maxTime: 60,
    materialsRequired: ['boxes', 'tape'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'medium',
    difficulty: 'hard',
  }),
  make({
    title: 'Kitchen Volcano',
    storyIntro: 'Deep in the kitchen mountains, a volcano is about to erupt. You control the lava!',
    mission: 'Make a fizzing eruption with kitchen ingredients.',
    objective: 'Create a foamy overflow that climbs out of the cup.',
    steps: [
      'Put two spoons of baking soda in a cup on a tray.',
      'Add a squirt of dish soap and a little food colouring if you have it.',
      'Pour in vinegar and watch it erupt.',
      'Try more or less vinegar to change the eruption.',
    ],
    safetyTips: ['Do this over a tray or sink.', 'Do not taste the mixture.'],
    learningExplanation:
      'Baking soda and vinegar react to make gas bubbles. That gas is what pushes the foam up.',
    reflectionQuestions: ['What made the bubbles?', 'How could you make a bigger eruption?'],
    parentTip: 'Let them run the experiment twice and compare.',
    category: 'science',
    skills: ['stem', 'observation'],
    minAge: 4,
    maxAge: 10,
    minTime: 15,
    maxTime: 25,
    materialsRequired: ['kitchen'],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'medium',
    difficulty: 'easy',
  }),
  make({
    title: 'Shadow Puppet Theatre',
    storyIntro: 'When the lights go low, your hands become dragons, rabbits, and birds!',
    mission: 'Create a short shadow-puppet story on the wall.',
    objective: 'Perform a story with at least three different shadow shapes.',
    steps: [
      'Point a lamp or flashlight at a blank wall.',
      'Make shapes with your hands in the light.',
      'Invent three characters.',
      'Tell a little story with them.',
    ],
    safetyTips: [],
    learningExplanation:
      'Objects block light to make shadows. Moving closer to the light makes shadows bigger.',
    reflectionQuestions: ['Why did the shadow get bigger?', 'What story did you tell?'],
    parentTip: 'Be an enthusiastic audience. Ask what happens next.',
    category: 'storytelling',
    skills: ['creativity', 'language', 'confidence'],
    minAge: 3,
    maxAge: 8,
    minTime: 10,
    maxTime: 20,
    materialsRequired: [],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Paper Airplane Squadron',
    storyIntro: 'The sky is calling! Design a plane that can fly further than any other.',
    mission: 'Fold a paper airplane and improve how far it flies.',
    objective: 'Make one that flies at least three big steps.',
    steps: [
      'Fold a simple paper airplane.',
      'Throw it and mark where it lands.',
      'Change one thing: the nose, the wings, or the folds.',
      'Test again and try to beat your distance.',
    ],
    safetyTips: ['Aim away from faces and windows.'],
    learningExplanation:
      'Wings create lift and a pointed nose cuts through air. Small changes change the flight a lot.',
    reflectionQuestions: ['Which change helped the most?', 'Why do you think it flew further?'],
    parentTip: 'Only change one thing at a time so they see cause and effect.',
    category: 'science',
    skills: ['stem', 'physics', 'motor'],
    minAge: 5,
    maxAge: 11,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['paper'],
    indoorOutdoor: 'either',
    weatherTags: ['any'],
    energyLevel: 'active',
    difficulty: 'medium',
  }),
  make({
    title: 'Nature Sound Map',
    storyIntro: 'Close your eyes. The park is full of secret sounds waiting to be discovered.',
    mission: 'Sit quietly outside and map every sound you hear.',
    objective: 'Find at least five different sounds and draw where each came from.',
    steps: [
      'Sit comfortably outside and stay still.',
      'Close your eyes for one minute and just listen.',
      'Draw a dot for yourself in the middle of a page.',
      'Mark each sound around you with a little drawing.',
    ],
    safetyTips: ['Stay where a grown-up can see you.'],
    learningExplanation:
      'Focused listening builds attention and awareness, a calm mindfulness skill.',
    reflectionQuestions: ['Which sound was closest?', 'Which was your favourite?'],
    parentTip: 'Do it with them and compare maps afterwards.',
    category: 'mindfulness',
    skills: ['observation', 'focus'],
    minAge: 4,
    maxAge: 10,
    minTime: 10,
    maxTime: 20,
    materialsRequired: ['paper', 'markers'],
    indoorOutdoor: 'outdoor',
    weatherTags: ['sunny', 'windy', 'any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Sink or Float Lab',
    storyIntro: 'The bathtub ocean needs a scientist! Which treasures will sink to the seabed?',
    mission: 'Test whether household objects sink or float.',
    objective: 'Sort at least six objects into sink and float piles.',
    steps: [
      'Fill a bowl or sink with water.',
      'Gather safe objects: a spoon, a cork, a toy, a coin.',
      'Guess first, then drop each one in.',
      'Sort them into two piles: sink and float.',
    ],
    safetyTips: ['Never leave young children alone near water.'],
    learningExplanation:
      'Heavy-for-their-size things sink; things full of air float. This is density in action.',
    reflectionQuestions: ['Which guess surprised you?', 'What did the floaters have in common?'],
    parentTip: 'Ask them to predict out loud before each test.',
    category: 'science',
    skills: ['stem', 'observation', 'problem_solving'],
    minAge: 3,
    maxAge: 8,
    minTime: 15,
    maxTime: 25,
    materialsRequired: ['water', 'kitchen'],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Balloon Rocket',
    storyIntro: 'Countdown to blast-off! Your balloon rocket is about to zoom across the room.',
    mission: 'Send a balloon flying along a string using only air.',
    objective: 'Make the balloon travel the full length of the string.',
    steps: [
      'Thread a long string through a drinking straw and tie it across the room.',
      'Blow up a balloon but do not tie it, pinch the end.',
      'Tape the balloon to the straw.',
      'Let go and watch it rocket along the string.',
    ],
    safetyTips: ['Uninflated balloons are a choking hazard for little ones.'],
    learningExplanation:
      'Air rushing out one way pushes the balloon the other way. That push is thrust, like a real rocket.',
    reflectionQuestions: ['Which way did the air go?', 'How could you make it go faster?'],
    parentTip: 'Try more air vs less air and compare speed.',
    category: 'science',
    skills: ['stem', 'physics'],
    minAge: 5,
    maxAge: 11,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['balloons', 'string', 'tape'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'active',
    difficulty: 'medium',
  }),
  make({
    title: 'Story Stones',
    storyIntro: 'Every stone holds a tiny story. Draw them, then let the stories tumble out!',
    mission: 'Draw pictures on paper tokens and use them to tell a story.',
    objective: 'Tell a story that uses at least four different tokens.',
    steps: [
      'Cut small circles of paper (or use flat stones).',
      'Draw a simple picture on each: a sun, a dog, a boat, a star.',
      'Shuffle them and pick four without looking.',
      'Make up a story that connects all four.',
    ],
    safetyTips: [],
    learningExplanation:
      'Linking random ideas into a story builds language, sequencing, and imagination.',
    reflectionQuestions: ['How did your story begin and end?', 'Which token was hardest to fit in?'],
    parentTip: 'Take turns adding a sentence each.',
    category: 'storytelling',
    skills: ['language', 'creativity', 'reading'],
    minAge: 4,
    maxAge: 9,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['paper', 'markers'],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Coin Counting Market',
    storyIntro: 'Welcome to your very own shop! Every toy has a price and you are the shopkeeper.',
    mission: 'Set up a pretend shop and add up prices with coins.',
    objective: 'Correctly add up the price of three items.',
    steps: [
      'Pick a few toys and give each a small price.',
      'Write the prices on paper labels.',
      'Be the customer and the shopkeeper.',
      'Count coins to pay for three items together.',
    ],
    safetyTips: ['Keep coins away from toddlers.'],
    learningExplanation: 'Handling coins turns abstract numbers into real, countable maths.',
    reflectionQuestions: ['How much did three toys cost?', 'What if the customer had less money?'],
    parentTip: 'Give them change to count back to you.',
    category: 'math',
    skills: ['stem', 'problem_solving', 'confidence'],
    minAge: 5,
    maxAge: 9,
    minTime: 15,
    maxTime: 30,
    materialsRequired: ['paper'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Obstacle Course Champion',
    storyIntro: 'The floor is lava and the couch is a mountain! Race through the wild course.',
    mission: 'Build and complete a living-room obstacle course.',
    objective: 'Finish the whole course three times, a little faster each try.',
    steps: [
      'Use cushions, chairs, and tape lines to make stations.',
      'Add moves: crawl under, jump over, spin around.',
      'Run the course once slowly to learn it.',
      'Time yourself and try to beat it.',
    ],
    safetyTips: ['Clear sharp corners and slippery rugs first.'],
    learningExplanation:
      'Planning a sequence and moving through it builds gross motor skills and memory.',
    reflectionQuestions: ['Which part was hardest?', 'How did you get faster?'],
    parentTip: 'Let them design it. Cheer loudly.',
    category: 'physical',
    skills: ['motor', 'confidence', 'problem_solving'],
    minAge: 3,
    maxAge: 10,
    minTime: 20,
    maxTime: 45,
    materialsRequired: [],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'active',
    difficulty: 'easy',
  }),
  make({
    title: 'Colour Hunt Safari',
    storyIntro: 'A rainbow escaped into the house! Track down every colour before it fades.',
    mission: 'Find one object for each colour of the rainbow.',
    objective: 'Collect or point to all seven rainbow colours.',
    steps: [
      'Name the rainbow colours together.',
      'Search the house or garden for one object of each colour.',
      'Line them up in rainbow order.',
      'Count how many you found.',
    ],
    safetyTips: [],
    learningExplanation:
      'Matching and ordering colours builds visual sorting and early pattern skills.',
    reflectionQuestions: ['Which colour was hardest to find?', 'What order do rainbow colours go in?'],
    parentTip: 'For older kids, add shades like light and dark blue.',
    category: 'art',
    skills: ['observation', 'motor'],
    minAge: 3,
    maxAge: 7,
    minTime: 10,
    maxTime: 20,
    materialsRequired: [],
    indoorOutdoor: 'either',
    weatherTags: ['any'],
    energyLevel: 'active',
    difficulty: 'easy',
  }),
  make({
    title: 'Egg Drop Engineer',
    storyIntro: 'A very brave egg wants to survive a great fall. Can you protect it?',
    mission: 'Build a package that keeps an egg safe when dropped.',
    objective: 'The egg survives a drop from standing height.',
    steps: [
      'Wrap an egg in a protective package using paper, tape, and boxes.',
      'Think about cushioning and a soft landing.',
      'Drop it from waist height first.',
      'If it survives, try a little higher.',
    ],
    safetyTips: ['Drop over a tray for easy cleanup.', 'Wash hands after handling raw egg.'],
    learningExplanation:
      'Cushioning spreads out the force of impact so the egg feels less of it. This is how crumple zones and helmets work.',
    reflectionQuestions: ['What protected the egg best?', 'What would you change next time?'],
    parentTip: 'Resist rescuing the design. A cracked egg is a great lesson.',
    category: 'engineering',
    skills: ['engineering', 'problem_solving', 'physics'],
    minAge: 6,
    maxAge: 12,
    minTime: 30,
    maxTime: 60,
    materialsRequired: ['paper', 'tape', 'boxes'],
    indoorOutdoor: 'either',
    weatherTags: ['any'],
    energyLevel: 'medium',
    difficulty: 'hard',
  }),
  make({
    title: 'Cloud Watching Journal',
    storyIntro: 'The sky is telling stories today. What shapes can you spot drifting by?',
    mission: 'Watch the clouds and draw what you see.',
    objective: 'Find and draw at least three cloud shapes.',
    steps: [
      'Lie back somewhere safe and look up.',
      'Watch the clouds for a few minutes.',
      'Draw three shapes you notice.',
      'Give each cloud a name or a story.',
    ],
    safetyTips: ['Never look directly at the sun.'],
    learningExplanation:
      'Noticing shapes and changes in the sky builds observation and imagination.',
    reflectionQuestions: ['Did the clouds change shape?', 'Which cloud told the best story?'],
    parentTip: 'Wonder aloud with them. No right answers here.',
    category: 'nature',
    skills: ['observation', 'creativity', 'focus'],
    minAge: 3,
    maxAge: 10,
    minTime: 10,
    maxTime: 20,
    materialsRequired: ['paper', 'markers'],
    indoorOutdoor: 'outdoor',
    weatherTags: ['sunny', 'windy'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),
  make({
    title: 'Junk Robot Friend',
    storyIntro: 'Hidden in the recycling is a robot waiting to be built. Give it a name and a job!',
    mission: 'Build a robot character from recycling and tape.',
    objective: 'Make a robot that can stand up on its own.',
    steps: [
      'Gather clean boxes, tubes, and containers from the recycling.',
      'Tape them together into a robot shape.',
      'Add a face with markers.',
      'Give your robot a name and a special power.',
    ],
    safetyTips: ['Use only clean, safe recycling.'],
    learningExplanation:
      'Turning waste into art builds creativity and shows that materials can have a second life.',
    reflectionQuestions: ['What is your robot’s job?', 'Which part was tricky to attach?'],
    parentTip: 'Let the design be theirs, even if it looks wobbly.',
    category: 'recycling',
    skills: ['creativity', 'motor', 'engineering'],
    minAge: 4,
    maxAge: 10,
    minTime: 30,
    maxTime: 60,
    materialsRequired: ['boxes', 'tape', 'markers'],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'medium',
    difficulty: 'medium',
  }),
  make({
    title: 'Secret Code Messages',
    storyIntro: 'Spies need a secret language. Invent a code only you and your partner can read!',
    mission: 'Create a picture code and write a secret message.',
    objective: 'Write a short message your partner can decode.',
    steps: [
      'Choose a picture for each letter you need, or shift letters by one.',
      'Write your key on one paper.',
      'Write a secret message using the code.',
      'Swap and decode each other’s messages.',
    ],
    safetyTips: [],
    learningExplanation:
      'Matching symbols to letters builds literacy and early logic and pattern thinking.',
    reflectionQuestions: ['Which letter was trickiest?', 'How did you crack the code?'],
    parentTip: 'Great for two children or a parent-child pair.',
    category: 'logic',
    skills: ['reading', 'problem_solving', 'language'],
    minAge: 6,
    maxAge: 12,
    minTime: 20,
    maxTime: 40,
    materialsRequired: ['paper', 'markers'],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'calm',
    difficulty: 'medium',
  }),
  make({
    title: 'Homemade Bird Feeder',
    storyIntro: 'The neighbourhood birds are hungry. Open a little restaurant just for them!',
    mission: 'Make a simple feeder and hang it outside.',
    objective: 'Hang your feeder and check it later for visitors.',
    steps: [
      'Poke small holes in a clean container and thread string through the top.',
      'Fill it with seeds or crumbs.',
      'Hang it on a branch or railing outside.',
      'Check back quietly through the day for birds.',
    ],
    safetyTips: ['Wash hands after handling seeds.', 'Ask a grown-up to help hang it high.'],
    learningExplanation:
      'Caring for animals builds empathy and teaches about local wildlife and habitats.',
    reflectionQuestions: ['What kinds of birds came?', 'How do you think they found the food?'],
    parentTip: 'Patience is the lesson. Check quietly, from a distance.',
    category: 'nature',
    skills: ['observation', 'social', 'motor'],
    minAge: 4,
    maxAge: 10,
    minTime: 20,
    maxTime: 40,
    materialsRequired: ['containers', 'string', 'kitchen'],
    indoorOutdoor: 'outdoor',
    weatherTags: ['sunny', 'cold', 'windy', 'any'],
    energyLevel: 'calm',
    difficulty: 'easy',
  }),

  // ---- Cooperative / sibling activities (Family mode) --------------------
  make({
    title: 'Blanket Fort Architects',
    storyIntro: 'Two builders, one epic fort. Can you design it together without knocking it down?',
    mission: 'Work as a team to build a blanket fort big enough to sit inside.',
    objective: 'Both of you fit inside your finished fort.',
    steps: [
      'Gather blankets, cushions, and chairs together.',
      'Agree on a plan: who holds, who drapes.',
      'Build the walls and roof as a team.',
      'Climb inside and admire your work.',
    ],
    safetyTips: ['Keep the structure low so nothing heavy can fall.'],
    learningExplanation:
      'Building together needs planning, negotiation, and cooperation, the heart of teamwork.',
    reflectionQuestions: ['What did you disagree about?', 'How did you solve it together?'],
    parentTip: 'Let them work out roles. Step in only if it stalls.',
    category: 'teamwork',
    skills: ['social', 'engineering', 'creativity'],
    minAge: 4,
    maxAge: 11,
    minTime: 20,
    maxTime: 45,
    materialsRequired: [],
    indoorOutdoor: 'indoor',
    weatherTags: ['rainy', 'cold', 'any'],
    energyLevel: 'active',
    difficulty: 'medium',
  }),
  make({
    title: 'Relay of Kindness',
    storyIntro: 'A team challenge where the prize is a happier home. Ready, set, help!',
    mission: 'Race the clock together to finish five small helpful tasks.',
    objective: 'Complete all five tasks as a team before the timer ends.',
    steps: [
      'Write five quick helpful tasks (tidy toys, water a plant, fold towels).',
      'Set a friendly timer.',
      'Split the tasks and cheer each other on.',
      'High-five when the last one is done.',
    ],
    safetyTips: [],
    learningExplanation:
      'Shared goals and encouragement build cooperation and a sense of contribution.',
    reflectionQuestions: ['Which task was most fun together?', 'How did helping feel?'],
    parentTip: 'Join in as a teammate, not a referee.',
    category: 'teamwork',
    skills: ['social', 'confidence', 'motor'],
    minAge: 3,
    maxAge: 10,
    minTime: 10,
    maxTime: 20,
    materialsRequired: [],
    indoorOutdoor: 'indoor',
    weatherTags: ['any'],
    energyLevel: 'active',
    difficulty: 'easy',
  }),

  // ---- Premium pack samples (gated) --------------------------------------
  make(
    {
      title: 'Astronaut Training Camp',
      storyIntro: 'Mission Control needs new astronauts! Complete your training to earn your wings.',
      mission: 'Complete three astronaut training challenges.',
      objective: 'Pass all three: balance, memory, and a spacewalk crawl.',
      steps: [
        'Balance test: stand on one foot and count to ten.',
        'Memory test: repeat a sequence of three sounds.',
        'Spacewalk: crawl across the room in slow motion.',
        'Earn your astronaut badge.',
      ],
      safetyTips: ['Clear the floor before the spacewalk crawl.'],
      learningExplanation:
        'Balance, memory, and body control are real skills astronauts train, and so can you.',
      reflectionQuestions: ['Which test was hardest?', 'Why do astronauts need good balance?'],
      parentTip: 'Play Mission Control and give the countdowns.',
      category: 'physical',
      skills: ['motor', 'focus', 'confidence'],
      minAge: 4,
      maxAge: 9,
      minTime: 20,
      maxTime: 40,
      materialsRequired: [],
      indoorOutdoor: 'indoor',
      weatherTags: ['rainy', 'cold', 'any'],
      energyLevel: 'active',
      difficulty: 'medium',
    },
    'space',
  ),
  make(
    {
      title: 'Deep Sea Explorer Bottle',
      storyIntro: 'Dive to the bottom of the ocean in a bottle and discover what lives in the deep.',
      mission: 'Make an ocean-in-a-bottle and spot the layers.',
      objective: 'See the oil and water settle into two clear layers.',
      steps: [
        'Fill a clear bottle halfway with water and a little blue colouring.',
        'Add cooking oil until nearly full.',
        'Seal it tightly and tip it side to side to make waves.',
        'Let it settle and watch the layers separate.',
      ],
      safetyTips: ['Seal the lid tightly.', 'Do this over a tray.'],
      learningExplanation:
        'Oil and water do not mix and oil is lighter, so it floats on top. That is density again.',
      reflectionQuestions: ['Why do the layers not mix?', 'Which liquid floats on top?'],
      parentTip: 'Ask them to predict which layer will be on top before it settles.',
      category: 'science',
      skills: ['stem', 'observation'],
      minAge: 4,
      maxAge: 10,
      minTime: 15,
      maxTime: 30,
      materialsRequired: ['water', 'kitchen', 'containers'],
      indoorOutdoor: 'indoor',
      weatherTags: ['rainy', 'cold', 'any'],
      energyLevel: 'calm',
      difficulty: 'easy',
    },
    'ocean',
  ),
  make(
    {
      title: 'Dinosaur Fossil Dig',
      storyIntro: 'A palaeontologist is needed! Ancient bones are hidden and waiting to be discovered.',
      mission: 'Hide and excavate pretend fossils.',
      objective: 'Find and identify all the hidden fossils.',
      steps: [
        'A grown-up hides small toys or drawn "fossils" in a tray of sand, rice, or crumpled paper.',
        'Use a spoon and brush to dig carefully.',
        'Lay out each fossil you find.',
        'Guess what dinosaur each one belongs to.',
      ],
      safetyTips: ['Keep small parts away from toddlers.'],
      learningExplanation:
        'Careful digging and record-keeping is exactly how real palaeontologists work.',
      reflectionQuestions: ['Which fossil was hardest to find?', 'How do scientists know about dinosaurs?'],
      parentTip: 'Number the fossils and have them dig in order for extra focus.',
      category: 'science',
      skills: ['observation', 'focus', 'stem'],
      minAge: 3,
      maxAge: 9,
      minTime: 20,
      maxTime: 40,
      materialsRequired: ['containers', 'kitchen'],
      indoorOutdoor: 'indoor',
      weatherTags: ['rainy', 'cold', 'any'],
      energyLevel: 'medium',
      difficulty: 'easy',
    },
    'dinosaur',
  ),
];

export const CURATED_COUNT = CURATED_ACTIVITIES.length;
